### PR TITLE
Fixed build on windows 

### PR DESCRIPTION
**Pull request by Ristaaf**
by replacing app\ts with js in windows style dirs, and not only Linux and OSX style dirs according to issue #43 But a bit cleaner solution

### CODE REVIEW

**Comment by bertrandk** [comment]
Thanks for the PR @Ristaaf! 

Looking at the problem, it seems like we should use `path.join` on the substring path instead of directly specifying the path separator (i.e. `path.join('app', 'ts')`). Running two optimistic replacements sort of hides the intent, imo.

**Comment by Ristaaf** [comment]
Agreed, there is some refactoring needed though, since the path used in gulp-rename is not the same as the node path that you get with require('path'). I will make a suggestion, and you can comment on that.

**Comment by igor-ka** [comment]
Hi @Ristaaf thanks for the contribution. The code looks good to me, however I am assigning this to @bertrandk as he reviewed its originally.

**Comment by bertrandk** [comment]
:+1: Looks great. Thanks a bunch @Ristaaf.

**Pull request merged**
