### PR TITLE
Add contribution guidelines

### PR DESCRIPTION
**Pull request by igor-ka**
- Add contribution guidelines
 - Minor fixes in README.md

This PR resolves issue #48

### CODE REVIEW

**Comment by igor-ka** [comment]
@vanessayuenn @winkerVSbecks @bertrandk 
Assigned this to Bertrand, but i think it would be worth having a look just in case i missed something.

cc @yuri

**Comment by winkerVSbecks** [comment]
Looks good to me. Not sure we need to include the coding style section. That stuff should just be enforced using tslint, editorconfig, etc. Also, we should get the CI up and running soon.

**Comment by bertrandk** [comment]
I few things I'd like to add:
- [ ] Add an MIT license
- [ ] Add commit message guidelines (as much as we care)
- [ ] Review that tslint is adequate and can be relied upon fully
  - I really want to avoid contributors having to revisit PRs for styleguide issues when the linter told them they were good
- [ ] Add actual, clickable, link to github issues (as the issue tracker)
- [ ] Expound on guidelines for contributions
  - just more details, especially with regards to how feature requests work
  - a solution to the "I'm new and don't even know where to get started" problem
    - the crux of the problem is that there's a lot of "out-of-band" stuff that occurs on projects (design docs, mental models, previous decisions, etc...)
    - we don't need a comprehensive solution in the PR but a dedicated "newcomer" slack/IRC channel and a paragraph directing them there might suffice

**Comment by igor-ka** [comment]
@bertrandk the license is already in the repo, do you want it to be added to the guidelines?

TsLint, I personally hate some of the rules that are in there, can we just pick something together that works?

**Comment by bertrandk** [comment]
A link should suffice for the LICENSE. It feels odd not mentioning it at all. I can also take a stab at one in the comments here and let you review it when you're free.

**Comment by bertrandk** [comment]
:ship: at will...

**Pull request merged**
