### PR TITLE
Feat/accordian

### PR DESCRIPTION
**Pull request by vanessayuenn**
- create accordian components
- move things in there by section

### CODE REVIEW

**Comment by sumitarora** [comment]
do we need `toolbarButtonGlyphs_2x.png` we have arrow svg in images https://github.com/rangle/batarangle/blob/master/images/triangle.svgz

**Comment by vanessayuenn** [comment]
I pulled that png straight from the chrome devtool. I figured we might need to make use of the other icons in the future.

**Comment by sumitarora** [comment]
There are already two images in the folder https://github.com/rangle/batarangle/tree/master/images can you remove those if not being used `statusbarButtonGlyphs.png` and `statusbarButtonGlyphs_2x.png`

**Comment by sumitarora** [comment]
:shipit:

**Pull request merged**
