### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vanessayuenn**
add [waffle board badge](http://waffle.io/rangle/batarangle)

### CODE REVIEW

**Comment by sumitarora** [comment]
It is not accessible if you are not logged in? Is this correct?

**Comment by vanessayuenn** [comment]
@sumitarora the waffle board is available to public since this is a public repo :)

**Comment by sumitarora** [comment]
yeap figured it out they don't allow public url's if not logged in.

**Comment by sumitarora** [comment]
:shipit:

**Pull request merged**
